import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Building2, Check, Clock3, Coins, TrendingUp, Wallet } from 'lucide-react'
import { useState } from 'react'
import { api } from '../api'
import { seedUnitApi, type RecoveryQuote } from '../features/seed-unit/api/seedUnit.api'
import { queryKeys } from '../shared/api/queryKeys'
import { errorMessage } from '../shared/api/errors'
import type { Holding, Idea, Ledger, Me } from '../types'
const number=new Intl.NumberFormat('ko-KR')
export function MyPage(){
 const client=useQueryClient();const [tab,setTab]=useState('wallet');const [quote,setQuote]=useState<RecoveryQuote|null>(null)
 const me=useQuery({queryKey:['legacy-me'],queryFn:()=>api<Me>('/me')});const ideas=useQuery({queryKey:queryKeys.ideas(),queryFn:()=>api<Idea[]>('/ideas')});const holdings=useQuery({queryKey:queryKeys.holdings,queryFn:seedUnitApi.holdings});const ledger=useQuery({queryKey:queryKeys.ledger,queryFn:()=>api<Ledger[]>('/ledger')})
 const quoteMutation=useMutation({mutationFn:seedUnitApi.recoveryQuote,onSuccess:setQuote});const recover=useMutation({mutationFn:seedUnitApi.recover,onSuccess:()=>{setQuote(null);void client.invalidateQueries({queryKey:queryKeys.holdings});void client.invalidateQueries({queryKey:['legacy-me']});void client.invalidateQueries({queryKey:queryKeys.ledger})}});const payout=useMutation({mutationFn:seedUnitApi.payout,onSuccess:()=>{void client.invalidateQueries({queryKey:['legacy-me']});void client.invalidateQueries({queryKey:queryKeys.ledger})}})
 return <div className="container"><div className="profile-head"><span className="avatar large">{me.data?.name[0]}</span><div><h1>{me.data?.name}</h1><p>@{me.data?.profileId} <span className="badge green"><Check/>이메일 인증</span> {me.data?.role==='COMPANY'&&<span className="badge"><Building2/>기업 인증</span>}</p></div><button className="btn ghost">프로필 수정</button></div><div className="summary-grid"><div className="panel"><Wallet/><span>사용 가능 포인트</span><b>{number.format(me.data?.points??0)} P</b></div><div className="panel"><Clock3/><span>회수 가능 잔액</span><b>{number.format(me.data?.pending??0)} P</b>{Boolean(me.data?.pending)&&<button className="btn ghost compact" onClick={()=>payout.mutate()}>지갑으로 받기</button>}</div><div className="panel"><TrendingUp/><span>보유 Seed Unit</span><b>{holdings.data?.reduce((s,h)=>s+h.units,0)??0} Unit</b></div></div><div className="tabs"><button className={tab==='wallet'?'active':''} onClick={()=>setTab('wallet')}>포인트 원장</button><button className={tab==='holdings'?'active':''} onClick={()=>setTab('holdings')}>보유 Unit</button><button className={tab==='feedback'?'active':''} onClick={()=>setTab('feedback')}>내 피드백</button><button className={tab==='contribution'?'active':''} onClick={()=>setTab('contribution')}>채택 기여</button><button className={tab==='company'?'active':''} onClick={()=>setTab('company')}>기업 관심</button></div>
 {tab==='wallet'&&<section className="panel table"><div className="table-head"><b>활동 내역</b><b>변동</b><b>일시</b></div>{ledger.data?.map(l=><div key={l.id}><span>{l.label}</span><b className={l.amount>0?'plus':'minus'}>{l.amount>0?'+':''}{l.amount} P</b><span>{l.at}</span></div>)}</section>}
 {tab==='holdings'&&<section className="holding-grid">{holdings.data?.map(h=><HoldingCard key={h.id} holding={h} idea={ideas.data?.find(i=>i.id===h.ideaId)} onRecover={()=>quoteMutation.mutate(h.id)}/>)}<div className="notice"><Coins/><span><b>가상 포인트 안내</b> Seed Unit은 현금화할 수 없으며 금전적 권리나 수익 배분을 의미하지 않습니다.</span></div></section>}
 {tab==='feedback'&&<section className="panel state">작성한 피드백은 아이디어 상세에서 수정·삭제할 수 있습니다.</section>}{tab==='contribution'&&<section className="panel state">채택 기여 3회 · 받은 기여 포인트 300P</section>}{tab==='company'&&<section className="panel state">관심을 표시한 아이디어와 문의가 이곳에 표시됩니다.</section>}
 {(quoteMutation.isError||recover.isError||payout.isError)&&<p className="form-error">{errorMessage(quoteMutation.error??recover.error??payout.error)}</p>}{quote&&<div className="modal-back"><section className="modal"><h2>Seed Unit 회수 확인</h2><div className="quote"><span>회수 Unit <b>{quote.units}</b></span><span>확정 현재가 <b>{quote.recoveryPrice} P</b></span><span>실현 포인트 <b>{quote.realizedAmount} P</b></span><span>즉시 지갑 지급 <b>{quote.walletPaidAmount} P</b></span><span>회수 가능 잔액 <b>{quote.pendingAmount} P</b></span></div><p>회수 요청 시 현재 가격이 확정되며 이후 가격 변동의 영향을 받지 않습니다.</p><div className="wizard-actions"><button className="btn ghost" onClick={()=>setQuote(null)}>취소</button><button className="btn primary" onClick={()=>recover.mutate(quote.lotId)}>회수 확정</button></div></section></div>}</div>
}
function HoldingCard({holding,idea,onRecover}:{holding:Holding;idea?:Idea;onRecover:()=>void}){return <article className="panel holding"><div><span className={`badge ${holding.unlocked?'green':'orange'}`}>{holding.unlocked?'회수 가능':'24시간 잠금'}</span><h3>{idea?.title}</h3><small>{holding.purchasedAt} 구매</small></div><div className="holding-values"><span>보유 <b>{holding.units} Unit</b></span><span>매수 원금 <b>{holding.units*holding.entryPrice} P</b></span><span>현재 가치 <b>{holding.units*(idea?.price??0)} P</b></span><span>손익 <b className={(idea?.price??0)>=holding.entryPrice?'plus':'minus'}>{((idea?.price??0)-holding.entryPrice)*holding.units} P</b></span></div><button className="btn ghost" disabled={!holding.unlocked} onClick={onRecover}>{holding.unlocked?'회수하기':'회수 대기'}</button></article>}
